### ISSUE TITLE
Silverstripe 3.2.* // composer // requirements not satisfiable

### ISSUE THREAD

**Issue by steiha** [g4b0/silverstripe-linkable-dataobjects#6]
Would be nice if it would support new silverstripe 3.2.\* version.

**Comment by g4b0** [comment]
Did you tested it against Silverstripe 3.2.*?

**Comment by jchenevey** [comment]
FWIW, we have this module installed (not via composer) and running fine on 3.5.x and 3.6.x sites.

**Comment by g4b0** [comment]
Requirements updated in master branch, and in tag 1.2.
Can you please check if it's possible now to install the module through composer in your sites?

Thanks

**Comment by steiha** [comment]
Thank you for looking into this old issue.
Meanwhile I updated my projects to newer versions.
But I just did an fresh install of SS 3.2. and added your module as dependency via composer.
Everything smooth now. 
Thank you.

**Comment by steiha** [comment]
Hi Gabriele,

found a tiny but important typo in the readme.md


composer require zirak/linkable-dataobject

should be with ‚s'
composer require zirak/linkable-dataobjects

Best Regards 

Stefan

**Comment by g4b0** [comment]
Fixed in master branch. Thanks a lot
